### ISSUE TITLE
No decimal point allowed for width + length of own package

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#29] opened 2021-03-26 07:32 UTC
![grafik](https://user-images.githubusercontent.com/52350973/112597731-ca9df280-8e0d-11eb-83fe-c01ec1174a91.png)

Height can contain a comma but width can not
(Above it says "Module version: 1.1.5")

**Comment by ngolatka** [comment] 2021-03-26 08:44
Confirmed. Strangely, length and width have the class `validate-digits` but height has `validate-number`.

Thanks for reporting this. We'll check it.

**Comment by ngolatka** [comment] 2021-03-26 09:24
> Above it says "Module version: 1.1.5"

Short explanation about that apparent mismatch (1.1.5 vs. 1.5.1): in the UI, you see the versions of various sub-modules/packages. The [meta-package](https://github.com/netresearch/dhl-shipping-m2)'s version is visible in your composer.lock. Look for `"name": "dhl/shipping-m2" and you'll see it.

**Comment by ngolatka** [comment] 2021-03-29 08:14
Will be fixed in the next version 2.0.0 (no exact ETA yet).

Because we want uniform input fields everywhere, regardless of the API, we'll allow decimal values even if the German DHL Paket API doesn't allow them. The value will be rounded (not cast to `int` anymore) in our module before being sent to the API.

**Comment by mam08ixo** [comment] 2021-04-12 09:34
[DHL Shipping version 2.0.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.0.0) now allows all dimensions to be entered as decimal values. However, due to the requirements of the DHL Paket API, they will be rounded to integer when requesting a shipping label.

**Closed by mam08ixo** 2021-04-12 09:34 UTC
Labels: bug
