### ISSUE TITLE
No shipment with given tracking number found

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-shipping-m2#23] opened 2021-01-18 16:07 UTC
## Preconditions 

- Magento 2.4.1
- dhl/shipping-m2 1.3.0

On some shipments an error is logged in exception.log as well as in dhl_paket.log that a shipment with this tracking number cannot be found.

## Steps to reproduce

- This happens when "Track Shipment" is clicked in admin area. Only the link to DHL is shown then, instead of the tracking info itself.

- This seems to only happen on all "predated" shipments, before the day they are predated to. 

## Expected Outcome

- popup is opened with tracking info

## Actual Outcome

- popup is opened with link to DHL (there the tracking info is correctly shown)
- error is logged to exception.log and dhl_paket.log
Exception:

```
[2021-01-18 15:39:22] dhlpaket.ERROR: Error:
Not Found
with response:
HTTP/1.1 404 Not Found
Date: Mon, 18 Jan 2021 15:39:22 GMT
Content-Type: application/problem+json
Content-Length: 97
Connection: keep-alive
Correlation-Id: 8a3b2528-2772-4521-8b3d-cd4fcb7e690b
Content-Language: en
access-control-allow-origin: *
access-control-allow-headers: origin,x-requested-with,accept,content-type,dhl-api-key
access-control-max-age: 3628800
access-control-allow-methods: GET,OPTIONS

{"title":"No result found","status":404,"detail":"No shipment with given tracking number found."}

when sending request:
GET /track/shipments?trackingNumber=anonymized&service=parcel-de&requesterCountryCode=DE&originCountryCode=DE&recipientPostalCode=78357&language=de HTTP/1.1
Host: api-eu.dhl.com
DHL-API-Key: anonymized
Accept: application/json

 {"request":"[object] (Nyholm\\Psr7\\Request: {})","response":"[object] (GuzzleHttp\\Psr7\\Response: {})","exception":"[object] (Http\\Client\\Exception\\HttpException(code: 404): Not Found at /home/xy/public_html/magento2/prod/releases/20210101121849/vendor/dhl/sdk-api-unified-tracking/src/Http/Plugin/TrackingErrorPlugin.php:124)","milliseconds":292} []

```

## Reason

I tested it using Postman and the DHL API indeed returns:

```
{
    "title": "No result found",
    "status": 404,
    "detail": "No shipment with given tracking number found."
}
```

However, if I leave the `recipientPostalCode` out, the API successfully returns the tracking info.
So it seems the API has an error here. Maybe it considers the postal code wrongly on predated shipments?

Here the response of the same request, just without postal code:

```
{
    "shipments": [
        {
            "serviceUrl": "https://www.dhl.de/de/privatkunden.html?piececode=anonymized&cid=anonymized",
            "id": "anonymized",
            "service": "parcel-de",
            "status": {
                "timestamp": "2021-01-18T15:00:00",
                "location": {
                    "address": {
                        "addressLocality": "Deutschland"
                    }
                },
                "statusCode": "transit",
                "status": "Die Sendung wurde abgeholt.",
                "description": "Die Sendung wurde abgeholt."
            },
            "details": {
                "totalNumberOfPieces": 1,
                "pieceIds": [
                    "anonymized"
                ]
            },
            "events": [
                {
                    "timestamp": "2021-01-18T15:00:00",
                    "location": {
                        "address": {
                            "addressLocality": "Deutschland"
                        }
                    },
                    "statusCode": "transit",
                    "status": "Die Sendung wurde abgeholt.",
                    "description": "Die Sendung wurde abgeholt."
                }
            ]
        }
    ]
}
```

I tested it on multiple shipments, always the same. The postal code is always correct and equals the postal code set in Business Portal, so that cannot be the error.
Due to privacy I left all personal data out. I can provide you some examples via email, if you let me know where to send it to.

**Comment by mam08ixo** [comment] 2021-01-18 16:18
Please send request & response for both cases to the [support address](https://github.com/netresearch/dhl-shipping-m2/blob/1.4.0/README.md#support). We will then forward the issue to the API developers.

**Comment by HenKun** [comment] 2021-01-18 16:35
Email is sent 👍

**Comment by mam08ixo** [comment] 2021-01-18 17:28
I can confirm the issue and sent a support request to the DHL help center.

**Comment by HenKun** [comment] 2021-01-18 17:58
Yes there is a reason we just found out recently. The `dhlshippingsolutions/dhlglobalwebservices/cut_off_time` setting came in with an update some time ago and is set to 00:00:00 initially. Because of that all created shipments are created after the cut off time and hence, one day is always added. I think this added day results in the shipment being considered as predated. We are about to switch the setting to 23:59:59 so all created shipments are before the cutoff time.

**Comment by mam08ixo** [comment] 2021-01-18 18:53
I see, so sending the next day as shipment date is not done intentionally. IIRC there is an open issue with the cut-off time configuration that may come into effect here. One day being added may be a bug rather than a misconfiguration. We plan to replace it by a day-based setting in the future

**Comment by HenKun** [comment] 2021-01-18 19:05
Correct, it is not intentionally. Can I see the ticket somewhere or is it internal?

**Comment by mam08ixo** [comment] 2021-01-18 19:06
It is internal, not a user-reported issue.

**Comment by ngolatka** [comment] 2021-01-18 19:42
@HenKun wrote:
> Email is sent

... and received.

**Comment by ngolatka** [comment] 2021-01-31 08:40
Short update: @mam08ixo is in contact with the API developer team at DHL. They are currently looking into the matter.

**Comment by mam08ixo** [comment] 2021-04-13 11:44
We did not receive a response from DHL that explains the cause or announces a fix.

However, [DHL Shipping v2.0.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.0.0) has the cut-off time calculation reworked. With this change and proper module configuration, shipments are no longer handed over the current day although announced for the next day.

Nothing more we can do about it, closing this.

**Closed by mam08ixo** 2021-04-13 11:44 UTC

**Comment by HenKun** [comment] 2021-04-13 11:47
@mam08ixo Does the cut-off time setting now has a "different" meaning? Or rather do we need to change/adopt the setting to the new function or should we keep the current setting?

**Comment by mam08ixo** [comment] 2021-04-13 11:50
@HenKun The setting has the same effect but, as announced earlier, it was moved and needs to be re-configured when upgrading to the new module version.
